### ISSUE TITLE
Missing VEGAS backend

### ISSUE THREAD

**Issue by paulray** [nanograv/pint_pal#33]
The file `plot_utils.py` has `markers` and `colorschemes` defined for many backends, but VEGAS is not included.

**Comment by rossjjennings** [comment]
We'll need to add in a color scheme for VEGAS for NG20, but we're running out of colors. Potentially we could retain the same colors used for the corresponding receivers with GUPPI, but just use a different symbol. We also might want to use a simpler color scheme by default, such as coloring by observatory only, rather than by receiver/backend combination.

**Comment by JPGlaser** [comment]
This was fixed by https://github.com/nanograv/pint_pal/pull/74

~ Joe G.
